kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-nfs-role-binding
subjects:
  - kind: ServiceAccount
    name: k8s-nfs
    namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-nfs-role
  apiGroup: rbac.authorization.k8s.io