apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "k8s-nfs.fullname" . }}
  labels:
    {{- include "k8s-nfs.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-nfs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-nfs.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "k8s-nfs.serviceAccountName" . }}
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: docker
              mountPath: "/var/run/docker.sock"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        - name: centos-nfs
          image: "centos/nfs:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                command: ["systemctl", "stop", "nfs"]
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          ports:
            - name: nfs
              hostPort: 2049
              containerPort: 2049
          volumeMounts:
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
      volumes:
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: docker
          hostPath:
            path: /var/run/docker.sock