{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-nfs.serviceAccountName" . }}
  labels:
{{ include "k8s-nfs.labels" . | nindent 4 }}
{{- end -}}

